#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.realpath File.join(__dir__, "..", "..", "lib")
require File.join(lib, "init")

##
# Database

def insert_book(book)
  DB[:books].insert(
    name: book.name,
    path: book.path
  )
end

def insert_chapter(chapter, book_id)
  DB[:chapters].insert(
    name: chapter.name,
    path: chapter.path,
    book_id:
  )
end

def insert_section(section, index, book_id, chapter_id)
  section_id = DB[:sections].insert(
    title: section.title, anchor: section.id,
    level: section.level, position: index,
    source_line: section.source_location&.lineno,
    text: section.chunk, chapter_id:
  )
  DB[:sections_fts].insert(
    title: section.title,
    text: section.chunk,
    section_id:, book_id:, chapter_id:
  )
end

##
# main

def main(argv)
  book    = Book.handbook
  book_id = insert_book(book)

  book.chapters.each do |chapter|
    puts "handbook: insert chapter #{chapter.name}"
    chapter_id = insert_chapter(chapter, book_id)
    puts "handbook: ok"
    chapter.sections.each_with_index do |section, index|
      puts "handbook: insert section"
      insert_section(section, index, book_id, chapter_id)
      puts "handbook: ok"
    end
  end
  puts "handbook: #{Book.database}"
end
main(ARGV)
