# frozen_string_literal: true

development:
  adapter: postgresql
  host: database.home.network
  port: 5432
  username: postgres
  password:
  database: bsd44_development

test:
  adapter: postgresql
  host: database.home.network
  port: 5432
  username: postgres
  password:
  database: bsd44_test

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: bsd44
  password: <%= ENV["BSD44_DB_PASSWORD"] %>
  database: bsd44