# frozen_string_literal: true

development:
  adapter: postgresql
  host: database.home.network
  port: 5432
  username: postgres
  password:
  database: rubydev_development

test:
  adapter: postgresql
  host: database.home.network
  port: 5432
  username: postgres
  password:
  database: rubydev_test

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: rubydev
  password: <%= ENV["RUBYDEV_DB_PASSWORD"] %>
  database: rubydev